forge "https://forgeapi.puppetlabs.com"

mod 'rtyler-jenkins', '1.7.0'
mod 'puppetlabs-vcsrepo', '2.3.0'
mod 'maestrodev-wget', '1.7.3'
mod 'hubspot-nexus',
    :git => 'https://github.com/hubspotdevops/puppet-nexus'

